### ISSUE TITLE
Not working in window

### ISSUE THREAD

**Issue by DaiMux1** [kip-app/kip#2]
### Current and expected behavior

I downloaded it but when I turn on the app, it automatically turns off

### Environment & Operating System

Window

**Comment by particle4dev** [comment]
@dai02012000 Thank you for reporting. We will fix it as soon as possible.
Can you tell me more about the version of Windows you are running (win 7, win 10)?

**Comment by DaiMux1** [comment]
@particle4dev I use Win 10

**Comment by particle4dev** [comment]
Fixed on 0.9.0
